flags:
  strptime:
    split-base: true
  threepenny-gui:
    rebug: false
    buildexamples: false
  HsOpenSSL:
    fast-bignum: false

packages:
- '.'
- core
- deps/threepenny-gui/
- deps/data-interval/
- deps/GiST-0.0.1/
- deps/wreq-0.4.0.0/
- deps/ordered-0.1
extra-deps: 
- GenericPretty-1.2.1
- HTTP-4000.3.3
- HUnit-1.3.1.1
- HsOpenSSL-0.11.1.1
- JuicyPixels-3.2.7.1
- MonadCatchIO-transformers-0.3.1.3
- QuickCheck-2.8.2
- SHA-1.6.4.2
- StateVar-1.1.0.4
- Stream-0.4.7.2
- adjunctions-4.3
- aeson-0.8.0.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- arrows-0.4.4.1
- asn1-encoding-0.9.4
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.0
- attoparsec-0.12.1.6
- attoparsec-enumerator-0.3.4
- base-orphans-0.5.4
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-5.3
- blaze-builder-0.4.0.2
- blaze-builder-enumerator-0.2.1.0
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- blaze-textual-0.2.1.0
- byteable-0.1.1
- bytestring-builder-0.10.8.1.0
- bytestring-mmap-0.2.2
- case-insensitive-1.2.0.6
- cereal-0.4.1.1
- clock-0.7.2
- cmark-0.5.2.1
- comonad-5
- conduit-1.2.6.6
- conduit-extra-1.1.13.1
- connection-0.2.5
- contravariant-1.4
- cookie-0.4.2
- crypto-api-0.13.2
- cryptohash-0.11.9
- cryptonite-0.16
- data-default-0.7.1
- data-default-class-0.1.1
- data-default-instances-base-0.1.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- digest-0.0.1.2
- distributive-0.5.0.2
- dlist-0.7.1.2
- enclosed-exceptions-1.0.1.1
- entropy-0.3.7
- enumerator-0.4.20
- exceptions-0.8.2.1
- extensible-exceptions-0.1.1.4
- extra-1.4.9
- filemanip-0.3.6.3
- free-4.12.4
- haddock-library-1.4.2
- hashable-1.2.4.0
- highlighting-kate-0.6.2
- hmatrix-0.17.0.2
- hmatrix-gsl-0.17.0.0
- hourglass-0.2.10
- hslua-0.4.1
- http-client-0.4.28
- http-client-tls-0.2.4
- http-conduit-2.1.10.1
- http-types-0.9.1
- hxt-9.3.1.15
- hxt-charproperties-9.2.0.1
- hxt-regex-xmlschema-9.2.0.2
- hxt-unicode-9.0.2.4
- iso8601-time-0.1.4
- json-0.9.1
- kan-extensions-5.0.1
- lattices-1.5.0
- lazysmallcheck-0.6
- lens-4.14
- lens-aeson-1.0.0.5
- lifted-base-0.2.3.6
- memory-0.13
- mime-mail-0.4.11
- mime-types-0.1.0.7
- mmorph-1.0.6
- monad-control-1.0.1.0
- monads-tf-0.1.0.3
- mtl-2.2.1
- network-2.6.2.1
- network-info-0.2.0.8
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.1.0
- ordered-0.1
- pandoc-1.17.1
- pandoc-types-1.16.1
- parallel-3.2.1.0
- parsec-3.1.11
- pem-0.2.2
- postgresql-libpq-0.9.1.1
- postgresql-simple-0.4.10.0
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- psqueues-0.2.2.1
- pureMD5-2.1.3
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-pcre-builtin-0.94.4.8.8.35
- regex-posix-0.95.2
- regex-tdfa-1.2.2
- resourcet-1.1.7.4
- safe-0.3.9
- scientific-0.3.4.7
- semigroupoids-5.0.1
- semigroups-0.18.1
- snap-core-0.9.8.0
- snap-server-0.9.5.1
- socks-0.5.5
- split-0.2.3.1
- stm-2.4.4.1
- storable-complex-0.2.2
- streaming-commons-0.1.15.5
- stringsearch-0.3.6.6
- syb-0.6
- tagged-0.8.4
- tagsoup-0.13.10
- tasty-0.11.0.3
- tasty-hunit-0.9.2
- temporary-1.2.0.4
- texmath-0.8.6.3
- text-1.2.2.1
- text-binary-0.2.1
- tf-random-0.5
- tls-1.3.8
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- universe-base-1.0.2.1
- universe-instances-base-1.0
- universe-reverse-instances-1.0
- unix-compat-0.4.2.0
- unordered-containers-0.2.7.1
- utf8-string-1.0.1.1
- uuid-1.3.12
- uuid-types-1.0.3
- vault-0.3.0.6
- vector-0.10.12.3
- vector-binary-instances-0.2.3.2
- void-0.7.1
- websockets-0.9.6.2
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- xml-1.3.14
- yaml-0.8.17.2
- zip-archive-0.3.0.2
- zlib-0.6.1.1
- zlib-bindings-0.1.1.5
- zlib-enum-0.2.3.1
- handa-gdata-0.7.0.3
- cmdargs-0.10.14
- strptime-1.0.10
- strptime-1.0.10
- ofx-0.4.0.4
- http-client-openssl-0.2.0.2
- websockets-snap-0.9.2.0
- extended-reals-0.2.2.0




resolver: ghc-7.10
