flags:
  strptime:
    split-base: true
  threepenny-gui:
    rebug: false
    buildexamples: false
packages:
- '.'
- deps/threepenny-gui-0.4.2.0/
- deps/data-interval/
- deps/strptime-1.0.10/
- deps/handa-gdata-0.7.0.3/
- deps/GiST-0.0.1/
- deps/ofx-0.4.0.4/
- deps/http-client-openssl-0.2.0.1/
- deps/extended-reals-0.2.1.0/
- deps/wreq-0.4.0.0/
- deps/websockets-snap-0.9.2.0/
extra-deps: []
resolver: lts-3.8
