flags:
  HsOpenSSL:
    fast-bignum: false
  snap-server:
    openssl: true

packages:
- '.'
- browser 
- browser/core
- deps/threepenny-gui/
- deps/data-interval/
- deps/hgdata
- deps/extended-reals/
- deps/GiST-0.0.1/
  # - location: deps/wreq-0.4.0.0/
  #  extra-dep: True
- deps/ordered-0.1
- deps/pipes-binary
- location : deps/postgresql-simple-0.4.10.0/
  extra-dep: True

extra-deps:
  - arrows-0.4.4.1
  - strptime-1.0.10
  - Stream-0.4.7.2
  - lazysmallcheck-0.6
  - pipes-network-0.6.4.1
  - snap-server-1.0.2.2
  - HsOpenSSL-0.11.4.9










apply-ghc-options: everything
ghc-options:
  "*": -opta-Wa,-mrelax-relocations=no

resolver: lts-8.20
