flags:
  snap-server:
    openssl: true

packages:
- plugins
- browser
- core

allow-newer: true

extra-deps:
  - deps/master-plan
  - deps/postgresql-simple
  - deps/ordered
  - deps/GiST
  - deps/extended-reals
  - deps/data-interval
  - deps/threepenny-gui

resolver: lts-12.1
