flags:
  HsOpenSSL:
    fast-bignum: false
  snap-server:
    openssl: true

packages:
- '.'
- browser
- browser/core
- location: deps/threepenny-gui/
  extra-dep: True
- location: deps/data-interval/
  extra-dep: True
- location: deps/extended-reals/
  extra-dep: True
- location: deps/GiST/
  extra-dep: True
- location: deps/ordered
  extra-dep: True
- location : deps/postgresql-simple
  extra-dep: True

extra-deps:
  - arrows-0.4.4.1
  - GenericPretty-1.2.1
  - strptime-1.0.10
  - Stream-0.4.7.2
  - lazysmallcheck-0.6
  - snap-server-1.0.2.2
  - HsOpenSSL-0.11.4.9
  - Only-0.1


resolver: lts-9.21
